import { isNative } from "../lib/platform";
import { LogoIcon } from "./LogoMark";

/* ── AuthSplash ───────────────────────────────────────────────────────
   The single brand-loading surface for the whole boot sequence: the
   Suspense fallback whenever a lazy chunk owns the full viewport
   (AuthScreen, PatientApp, …), the auth/role-loading gate, AND the MFA
   gate's "checking factors" phase. Reusing ONE component everywhere is
   what keeps the cold start from flashing different layouts between
   states — every loading frame is the same logo on the same background,
   so the boot reads as one continuous splash that resolves into the app.

   On native (Capacitor), the surface matches the iOS LaunchScreen +
   SplashScreen plugin pixel-for-pixel: solid teal background, large
   centered white mark, no wordmark. iOS shows three potential splashes
   in sequence on cold start — LaunchScreen.storyboard (immediate,
   native), the SplashScreen plugin overlay (once the WebView starts),
   and React's first paint. Matching all three means the boot is a single
   uninterrupted teal-on-white-logo frame until the app paints. */
export function AuthSplash() {
  if (isNative()) {
    return (
      <div
        aria-hidden="true"
        style={{
          position: "fixed",
          inset: 0,
          background: "#5B9BAF",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}>
        <span
          className="cardigan-splash-logo"
          style={{
            /* 22% of the shorter viewport edge matches the splash.png
               mark ratio generated by scripts/generate-splash.mjs (which
               iOS displays as scaleAspectFit). Bounded so it stays
               sensible on tiny + tablet sizes. The inner SVG inherits
               this via width:100%. */
            width: "min(22vw, 22vh, 200px)",
            maxWidth: 240,
            display: "inline-flex",
          }}>
          <LogoIcon size="100%" color="#FFFFFF" />
        </span>
      </div>
    );
  }
  return (
    <div className="shell" style={{ justifyContent: "center", alignItems: "center", gap: 12 }}>
      <span className="cardigan-splash-logo" aria-hidden="true">
        <LogoIcon size={48} color="var(--teal)" />
      </span>
      <div style={{ fontFamily: "var(--font-d)", fontSize: 22, fontWeight: 800, color: "var(--charcoal)", letterSpacing: "-0.3px" }}>cardigan</div>
    </div>
  );
}
