/* ── GET /api/calendar/<token> ──
   Public iCalendar (.ics) feed. The token IS the credential — no JWT,
   because calendar clients can't carry one. The token is generated by
   the user via /api/calendar-token and rotated/revoked from Settings.

   Security model: anyone who has the URL can read the user's session
   list. Mitigations:
     - 32-byte CSPRNG token, base64url-encoded → unguessable
     - Rotation = upsert with a new token, breaking existing
       subscriptions on demand (Settings exposes the button)
     - The feed body uses the full patient name in SUMMARY so the
       therapist can read their own calendar at a glance; this means
       a leaked URL exposes those names to whoever has it. The user-
       facing copy where the URL is shown must communicate that.
     - last_accessed_at is updated so the user can see whether the
       feed is in active use before rotating

   URL convention: clients sometimes append a `.ics` suffix to the
   token to satisfy content-type sniffing. We strip a trailing .ics
   from the param so both `/api/calendar/<tok>` and
   `/api/calendar/<tok>.ics` resolve to the same row. */

import crypto from "node:crypto";
import { getServiceClient } from "../_admin.js";
import { withSentry } from "../_sentry.js";
import { generateICS } from "../_calendar.js";

function hashToken(token) {
  // SHA-256 hex — matches `encode(digest(token, 'sha256'), 'hex')`
  // in supabase/migrations/026 and the create-side hash in
  // api/calendar-token.js. Same input → same hex byte-for-byte.
  return crypto.createHash("sha256").update(token).digest("hex");
}

async function handler(req, res) {
  if (req.method !== "GET" && req.method !== "HEAD") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const raw = req.query?.token;
  const tokenParam = Array.isArray(raw) ? raw[0] : raw;
  if (!tokenParam || typeof tokenParam !== "string") {
    return res.status(404).json({ error: "Not found" });
  }
  const token = tokenParam.replace(/\.ics$/i, "");
  // Cheap guard against malformed input flooding the DB. base64url
  // tokens are at most ~88 chars for 64 bytes; we only issue ~43 chars.
  if (token.length < 16 || token.length > 128 || !/^[A-Za-z0-9_-]+$/.test(token)) {
    return res.status(404).json({ error: "Not found" });
  }

  const svc = getServiceClient();
  // Look up by SHA-256 hash — the plaintext token isn't stored in
  // the DB (migration 026). Hash is unique per row.
  const tokenHash = hashToken(token);

  const { data: row, error } = await svc
    .from("user_calendar_tokens")
    .select("user_id")
    .eq("token_hash", tokenHash)
    .maybeSingle();

  if (error) return res.status(500).json({ error: "Lookup failed" });
  if (!row) return res.status(404).json({ error: "Not found" });

  // Pull the user's sessions + their preferred timezone in parallel.
  // Cancelled / charged rows are EXCLUDED — when a session is cancelled
  // the therapist wants it gone from their phone calendar entirely, not
  // shown with a strikethrough. Calendar clients (Apple Calendar, Google,
  // Outlook) diff each refresh against the previous fetch and remove
  // events that disappeared from the feed, so once a session moves to
  // 'cancelled' it'll drop out of the user's calendar on the next sync
  // (typically within an hour).
  // We also exclude rows older than 1 year so the feed doesn't grow
  // unbounded — calendar clients only render the visible window anyway.
  const oneYearAgo = new Date();
  oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1);

  const [sessionsRes, prefsRes] = await Promise.all([
    svc
      .from("sessions")
      .select("id, date, time, duration, status, patient, initials, modality, cancel_reason")
      .eq("user_id", row.user_id)
      .in("status", ["scheduled", "completed"])
      .gte("created_at", oneYearAgo.toISOString())
      .limit(5000),
    svc
      .from("notification_preferences")
      .select("timezone")
      .eq("user_id", row.user_id)
      .maybeSingle(),
  ]);

  if (sessionsRes.error) {
    return res.status(500).json({ error: "Failed to read sessions" });
  }

  const timezone = prefsRes?.data?.timezone || "America/Mexico_City";
  const body = generateICS({
    sessions: sessionsRes.data || [],
    timezone,
    calendarName: "Cardigan",
  });

  // Best-effort touch — failure here doesn't hurt the response.
  svc
    .from("user_calendar_tokens")
    .update({ last_accessed_at: new Date().toISOString() })
    .eq("token_hash", tokenHash)
    .then(() => {}, () => {});

  res.setHeader("Content-Type", "text/calendar; charset=utf-8");
  // Don't let intermediate caches hold a stale snapshot — when the
  // user cancels a session we want the next client poll to see fresh
  // data, not whatever a CDN has cached from 5 minutes ago. Pair this
  // with REFRESH-INTERVAL inside the body which controls how often
  // the client itself polls.
  res.setHeader("Cache-Control", "private, no-cache, no-store, must-revalidate");
  res.setHeader("Content-Disposition", "inline; filename=cardigan.ics");
  res.status(200).send(body);
}

export default withSentry(handler, { name: "calendar-feed" });
