/* ── GET /api/calendar/<token> ──
   Public iCalendar (.ics) feed. The token IS the credential — no JWT,
   because calendar clients can't carry one. The token is generated by
   the user via /api/calendar-token and rotated/revoked from Settings.

   Security model: anyone who has the URL can read the user's session
   list. Mitigations:
     - 32-byte CSPRNG token, base64url-encoded → unguessable
     - Rotation = upsert with a new token, breaking existing
       subscriptions on demand (Settings exposes the button)
     - The feed body uses the full patient name in SUMMARY so the
       therapist can read their own calendar at a glance; this means
       a leaked URL exposes those names to whoever has it. The user-
       facing copy where the URL is shown must communicate that.
     - last_accessed_at is updated so the user can see whether the
       feed is in active use before rotating

   URL convention: clients sometimes append a `.ics` suffix to the
   token to satisfy content-type sniffing. We strip a trailing .ics
   from the param so both `/api/calendar/<tok>` and
   `/api/calendar/<tok>.ics` resolve to the same row. */

import crypto from "node:crypto";
import { getServiceClient } from "../_admin.js";
import { withSentry } from "../_sentry.js";
import { generateICS } from "../_calendar.js";

function hashToken(token) {
  // SHA-256 hex — matches `encode(digest(token, 'sha256'), 'hex')`
  // in supabase/migrations/026 and the create-side hash in
  // api/calendar-token.js. Same input → same hex byte-for-byte.
  return crypto.createHash("sha256").update(token).digest("hex");
}

async function handler(req, res) {
  if (req.method !== "GET" && req.method !== "HEAD") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const raw = req.query?.token;
  const tokenParam = Array.isArray(raw) ? raw[0] : raw;
  if (!tokenParam || typeof tokenParam !== "string") {
    return res.status(404).json({ error: "Not found" });
  }
  const token = tokenParam.replace(/\.ics$/i, "");
  // Cheap guard against malformed input flooding the DB. base64url
  // tokens are at most ~88 chars for 64 bytes; we only issue ~43 chars.
  if (token.length < 16 || token.length > 128 || !/^[A-Za-z0-9_-]+$/.test(token)) {
    return res.status(404).json({ error: "Not found" });
  }

  const svc = getServiceClient();
  // Look up by SHA-256 hash — the plaintext token isn't stored in
  // the DB (migration 026). Hash is unique per row.
  const tokenHash = hashToken(token);

  const { data: row, error } = await svc
    .from("user_calendar_tokens")
    .select("user_id")
    .eq("token_hash", tokenHash)
    .maybeSingle();

  if (error) return res.status(500).json({ error: "Lookup failed" });
  if (!row) return res.status(404).json({ error: "Not found" });

  // Pull the user's sessions + their preferred timezone in parallel.
  // Cancelled / charged rows are EXCLUDED — when a session is cancelled
  // the user wants it gone from their phone calendar entirely, not
  // shown with a strikethrough. Calendar clients (Apple Calendar, Google,
  // Outlook) diff each refresh against the previous fetch and remove
  // events that disappeared from the feed, so once a session moves to
  // 'cancelled' it'll drop out of the user's calendar on the next sync
  // (typically within an hour).
  // We also exclude rows older than 1 year so the feed doesn't grow
  // unbounded — calendar clients only render the visible window anyway.
  const oneYearAgo = new Date();
  oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1);

  // Determine if the token's owner is a therapist (sessions match by
  // sessions.user_id — the original flow) or a patient (sessions
  // match by patient_id IN (linked patient rows)). Patient feeds
  // are scoped to their OWN sessions only — they never see the
  // therapist's other patients' calendars.
  const { data: linkedPatients } = await svc
    .from("patients")
    .select("id")
    .eq("patient_user_id", row.user_id)
    .in("status", ["active", "potential"]);
  const isPatient = (linkedPatients?.length || 0) > 0;
  const linkedPatientIds = (linkedPatients || []).map((p) => p.id);

  const sessionsBaseSelect = "id, date, time, duration, status, patient, initials, modality, cancel_reason, session_type";
  const sessionsQuery = isPatient
    ? svc
        .from("sessions")
        .select(sessionsBaseSelect)
        .in("patient_id", linkedPatientIds)
        .in("status", ["scheduled", "completed"])
        .gte("created_at", oneYearAgo.toISOString())
        .limit(5000)
    : svc
        .from("sessions")
        .select(sessionsBaseSelect)
        .eq("user_id", row.user_id)
        .in("status", ["scheduled", "completed"])
        .gte("created_at", oneYearAgo.toISOString())
        .limit(5000);

  const [sessionsRes, prefsRes] = await Promise.all([
    sessionsQuery,
    svc
      .from("notification_preferences")
      .select("timezone")
      .eq("user_id", row.user_id)
      .maybeSingle(),
  ]);

  if (sessionsRes.error) {
    return res.status(500).json({ error: "Failed to read sessions" });
  }

  const timezone = prefsRes?.data?.timezone || "America/Mexico_City";

  // Patient feeds get a subject override so SUMMARY reads "Sesión
  // con {therapist}" instead of "Sesión - {patient}". Resolve the
  // therapist's display name from auth.users.user_metadata —
  // service-role client can read this. Falls back to "tu
  // profesionista" if user_metadata is empty.
  let subjectOverride = null;
  if (isPatient) {
    // The patient might be linked to multiple therapists. v1 UI
    // only shows one at a time and the iCal feed mirrors that — we
    // pull the therapist of the FIRST linked patient row. (When
    // multi-therapist UI ships, we'd switch to per-row VEVENTs
    // with distinct SUMMARY subjects.)
    const firstLinked = linkedPatients[0];
    const { data: linkedRow } = await svc
      .from("patients")
      .select("user_id")
      .eq("id", firstLinked.id)
      .maybeSingle();
    if (linkedRow?.user_id) {
      const { data: therapistRow } = await svc.auth.admin.getUserById(linkedRow.user_id);
      const meta = therapistRow?.user?.user_metadata || {};
      subjectOverride = meta.full_name
        || therapistRow?.user?.email?.split("@")[0]
        || "tu profesionista";
    }
  }

  const body = generateICS({
    sessions: sessionsRes.data || [],
    timezone,
    calendarName: isPatient ? "Cardigan" : "Cardigan",
    subjectOverride,
  });

  // Best-effort touch — failure here doesn't hurt the response.
  svc
    .from("user_calendar_tokens")
    .update({ last_accessed_at: new Date().toISOString() })
    .eq("token_hash", tokenHash)
    .then(() => {}, () => {});

  res.setHeader("Content-Type", "text/calendar; charset=utf-8");
  // Don't let intermediate caches hold a stale snapshot — when the
  // user cancels a session we want the next client poll to see fresh
  // data, not whatever a CDN has cached from 5 minutes ago. Pair this
  // with REFRESH-INTERVAL inside the body which controls how often
  // the client itself polls.
  res.setHeader("Cache-Control", "private, no-cache, no-store, must-revalidate");
  res.setHeader("Content-Disposition", "inline; filename=cardigan.ics");
  res.status(200).send(body);
}

export default withSentry(handler, { name: "calendar-feed" });
