#!/usr/bin/env node
/* ── sync-fonts.mjs ──
   Vendor Google Fonts locally so we can drop fonts.googleapis.com /
   fonts.gstatic.com from the CSP and stop leaking user IPs to Google
   on every page load.

   Usage:   node scripts/sync-fonts.mjs
   Outputs:
     public/fonts/<family>-<weight>-<subset>.woff2
     src/styles/fonts.css       — @font-face block per (weight, subset)

   Adjust FONTS_QUERY below to add weights or families. Subsets are
   pinned to latin + latin-ext (Spanish needs ext for ñ/á/é/í/ó/ú/ü).
   Cyrillic / Vietnamese subsets are dropped — dead weight on a
   Spanish-only app. */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const FONTS_DIR = join(ROOT, "public", "fonts");
const CSS_OUT = join(ROOT, "src", "styles", "fonts.css");

const FONTS_QUERY = "family=Nunito:wght@400;600;700;800&family=Nunito+Sans:wght@300;400;500;600&display=swap";
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

// Safari UA gets the most-compatible woff2 + best subset coverage.
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15";

mkdirSync(FONTS_DIR, { recursive: true });

const cssRes = await fetch(`https://fonts.googleapis.com/css2?${FONTS_QUERY}`, {
  headers: { "User-Agent": UA },
});
if (!cssRes.ok) {
  console.error(`Failed to fetch Google Fonts CSS: ${cssRes.status}`);
  process.exit(1);
}
const cssText = await cssRes.text();

// Parse @font-face blocks, each preceded by a /* subset */ comment.
const blocks = [...cssText.matchAll(/\/\*\s*([^*]+?)\s*\*\/\s*@font-face\s*\{([^}]+)\}/gs)];
const records = [];
for (const [, label, body] of blocks) {
  if (!KEEP_SUBSETS.has(label.trim())) continue;
  const fam = body.match(/font-family:\s*'([^']+)'/)?.[1];
  const wt = body.match(/font-weight:\s*(\d+)/)?.[1];
  const url = body.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/)?.[1];
  const range = body.match(/unicode-range:\s*([^;]+);/)?.[1].trim();
  if (!fam || !wt || !url || !range) continue;
  const slug = fam.toLowerCase().replace(/\s+/g, "-");
  records.push({ family: fam, weight: wt, subset: label.trim(), url, range, filename: `${slug}-${wt}-${label.trim()}.woff2` });
}

console.log(`${records.length} font-face blocks to vendor`);

const seen = new Set();
for (const r of records) {
  const dest = join(FONTS_DIR, r.filename);
  if (seen.has(r.url) || existsSync(dest)) { seen.add(r.url); continue; }
  console.log(`  ↓ ${r.filename}`);
  const res = await fetch(r.url, { headers: { "User-Agent": UA } });
  if (!res.ok) { console.error(`  ✗ failed: ${res.status}`); process.exit(1); }
  const buf = Buffer.from(await res.arrayBuffer());
  writeFileSync(dest, buf);
  seen.add(r.url);
}

const out = [
  "/* ── Self-hosted Nunito + Nunito Sans (latin + latin-ext) ──",
  "   Generated by scripts/sync-fonts.mjs. Don't hand-edit; re-run",
  "   the script if you need new weights or subsets. */",
  "",
];
for (const r of records) {
  out.push(`/* ${r.subset} */`);
  out.push("@font-face {");
  out.push(`  font-family: '${r.family}';`);
  out.push("  font-style: normal;");
  out.push(`  font-weight: ${r.weight};`);
  out.push("  font-display: swap;");
  out.push(`  src: url('/fonts/${r.filename}') format('woff2');`);
  out.push(`  unicode-range: ${r.range};`);
  out.push("}");
  out.push("");
}
writeFileSync(CSS_OUT, out.join("\n"));
console.log(`Wrote ${CSS_OUT} (${records.length} @font-face blocks)`);
