-- 079_sessions_user_date_index.sql
-- Composite (user_id, date) index on sessions to speed the common
-- "this user's sessions on a given day" access pattern (Agenda day view,
-- per-date filters) that today leans on idx_sessions_user_id alone.
--
-- HONEST CAVEAT: sessions.date is a "D-MMM" Spanish short-date STRING
-- (e.g. "8-Abr"), not an ISO date. So this index accelerates EQUALITY on
-- an exact date string (user_id = X AND date = '8-Abr'), NOT chronological
-- range scans (BETWEEN two months) — strings don't sort by calendar
-- order. The real range-scan fix is a proper ISO `date` column, which is
-- deliberately OUT OF SCOPE here because it touches the date-format
-- invariant threaded through parsers, triggers, and the accounting audit.
--
-- STATUS: PENDING — not yet applied to live as of this commit. schema.sql
-- and schema.snapshot.json deliberately do NOT carry this index yet so the
-- committed state stays consistent with production. To land it:
--   1. Apply via the Supabase Management API query endpoint (NOT a wrapped
--      runner — CONCURRENTLY cannot run inside a transaction block):
--        curl -X POST .../v1/projects/{ref}/database/query \
--          -d '{"query":"<the create index statement below>"}'
--   2. Move the index line into supabase/schema.sql (next to the other
--      sessions indexes).
--   3. Regenerate the snapshot so schema-drift CI stays green:
--        node --env-file=.env.local scripts/schema-snapshot.mjs --update
--
-- Apply with CONCURRENTLY so it never blocks writes on a large sessions table.
create index concurrently if not exists idx_sessions_user_date
  on public.sessions (user_id, date);
